# Generated by Django 4.2.30 on 2026-07-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee_tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMP_NAME", models.CharField(max_length=300)),
                ("EMP_DES", models.CharField(max_length=300)),
                ("EMP_Place", models.CharField(max_length=300)),
            ],
        ),
    ]
