# Generated by Django 4.2.30 on 2026-07-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Employee_tables", new_name="Employee_table",),
    ]
